### ISSUE TITLE
Potential typo in TestTrans.cpp

### ISSUE THREAD

**Issue by hptechdesign** [jondurrant/RPI-PicoW-WolfSSL-Exp#1]
Hello, and thanks for the great video and supporting repo. 

I'm in the early stages of working through these - I've cloned the repo and set up my environment variables. When I build, the WIFI_SSID variable is being set and declared but WIFI_PASSWORD is not. 

I'm working through that issue, assuming it is something I've done. Incidentally - and presumably unrelated - I found what looks like an error.

In line 74 of TestTrans.cpp:

`if (WifiHelper::join(WIFI_SSID, **WIFI_SSID**)){`

Should it not be

`if (WifiHelper::join(WIFI_SSID, **WIFI_PASSWORD**)){` ?

**Comment by jondurrant** [comment]
You are absolutely right. Apologies for letting this one slip in. It still worked  for me as it is joining on line 111 of main.cpp. 

Hope this fixes the issue. If not I have had some Wifi connectivity issues when the Pico-W is short of power in the past. Just in case your problem isn't really with credentials.

**Comment by hptechdesign** [comment]
That's a fast response - caused no issue for me yet since I'm still debugging compile errors in main.cpp.

I'm hitting #error "WIFI_PASSWORD not defined"  on line 32 of main.cpp, despite WIFI_SSID being found and both SSID and PASSWORD being set up apparently correctly. I'm sure it will be something I'm doing wrong, but if not and I find anything in the code I'll let you know. 

Thanks.

**Comment by hptechdesign** [comment]
An update on my remaining error - it is not an issue with your code.

There is however a limitation in CMake's _target_compile_definitions_ which looks to be causing an issue with at least one of the special characters ('#') in my WiFI password - more details here:
https://cmake.org/cmake/help/latest/prop_tgt/COMPILE_DEFINITIONS.html

I'll work around this but it might be worth adding a comment somewhere as it may catch others out too.

All best,
Huw

**Comment by jondurrant** [comment]
Ow that is pain. You could just hard code the password into main. I just
try to avoid that as don't want to place my password on GitHub.
